Description: |
  Capstone Project CloudFormation Servers Deployment.
  - Launch Configuration and Group
  - Application Load Balancer
  - Bastion Host
  - IAM Service Role
  - Security Group

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names.
    Type: String
    
  EksRole:
    Description: Role Assigned to the EKS Cluster
    Type: String
    Default: arn:aws:iam::628641662978:role/eksServiceRole

  EksNodeRole:
    Description: Role Assigned to the EKS NodeGroup
    Type: String
    Default: arn:aws:iam::628641662978:role/NodeInstanceRole

Resources:

  EKSSECURITUGROUP:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: EKS Cluster Security Group
      Tags: 
        - Key: Environment
          Value: !Ref EnvironmentName
        -
          Key: Name
          Value: !Sub ${EnvironmentName}-WEBSERVERGROUP
      VpcId:
        Fn::ImportValue: capstone-stack-VPC

  EKSSECURITUGROUPINGRESS:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EKSSECURITUGROUP
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref EKSSECURITUGROUP

  EKSCLUSTER:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: EKSCLUSTER
      Version: '1.15'
      RoleArn: !Ref EksRole
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EKSSECURITUGROUP
        SubnetIds:
          - Fn::ImportValue: capstone-stack-PUBSUBNET1
          - Fn::ImportValue: capstone-stack-PUBSUBNET2

  EKSNODEGROUP:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Ref EKSCLUSTER
      NodeRole: !Ref EksNodeRole
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 3
      Subnets:
        - Fn::ImportValue: capstone-stack-PUBSUBNET1
        - Fn::ImportValue: capstone-stack-PUBSUBNET2